### ISSUE TITLE
Docs display error with ForATime and Forever

### ISSUE THREAD

**Issue by mgold** [imeckler/stage#1]
In the [main module docs](http://package.elm-lang.org/packages/imeckler/stage/1.5.0/Stage), the following error:

type alias Stage t a = I.Stage t a
There is some problem with the docs for 'ForATime', please inform the package author.
There is some problem with the docs for 'Forever', please inform the package author.

Perhaps the type tags aren't exported? But it could be something else entirely (like a syntax issue). You may have some luck running `elm-doc` and examining the JSON.

**Comment by imeckler** [comment]
This is an issue with elm-doc. There's an issue [over here](https://github.com/elm-lang/elm-compiler/issues/881).
